"""
NOTE: This file was generated by AI based off of src/population_syste.py, which was written by Daniel Krawciw.
It is meant to be an importable version of the original script
"""


from pathlib import Path

import matplotlib.pyplot as plt
import seaborn as sns
import torch
from tqdm import tqdm

"""Plot setup"""
sns.set_style("whitegrid")
sns.set_color_codes(palette="colorblind")

plt.rcParams.update({
    "text.usetex": False,  # keep False to avoid requiring a LaTeX installation
    "mathtext.fontset": "cm",  # Computer Modern (LaTeX-like)
    "font.family": "serif",
    "font.serif": ["Computer Modern Roman", "DejaVu Serif"],
    "axes.labelsize": 14,
    "axes.titlesize": 16,
    "xtick.labelsize": 14,
    "ytick.labelsize": 14,
    "legend.fontsize": 12,
})

OUTPUT_DIR = Path(__file__).parent.parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)


class PopulationSystem:
    """Torch RK2 solver for the two-population ODE system."""

    def __init__(
        self,
        t_range=(0.0, 1.0),
        n_t=100,
        dtype=torch.float64,
        device="cpu",
    ):
        self.t_range = t_range
        self.n_t = n_t
        self.dtype = dtype
        self.device = torch.device(device)
        self.t_vals = torch.linspace(
            t_range[0],
            t_range[1],
            n_t,
            dtype=dtype,
            device=self.device,
        )
        self.delta_t = self.t_vals[1] - self.t_vals[0]

    def rhs(self, t, x, parameters):
        """Evaluate the population system dx/dt."""
        a = parameters
        dx1 = a[0] * x[0] - a[1] * x[0] * x[1]
        dx2 = a[2] * x[1] + a[3] * x[0] * x[1] - a[4] * x[1] ** 2
        return torch.stack([dx1, dx2])

    def rk2_step(self, t, x, parameters):
        """Advance one time step with midpoint RK2."""
        k1 = self.rhs(t, x, parameters)
        k2 = self.rhs(t + self.delta_t / 2, x + self.delta_t / 2 * k1, parameters)
        return x + self.delta_t * k2

    def solve(self, initial_condition, parameters, show_progress=False):
        """Solve the ODE system and return a trajectory with shape (n_t, 2)."""
        x = torch.as_tensor(initial_condition, dtype=self.dtype, device=self.device)
        parameters = torch.as_tensor(parameters, dtype=self.dtype, device=self.device)

        trajectory = [x]
        iterator = self.t_vals[1:]
        if show_progress:
            iterator = tqdm(iterator, desc="Solving population system")

        for t in iterator:
            x = self.rk2_step(t, x, parameters)
            trajectory.append(x)

        return torch.stack(trajectory)

    def default_initial_condition(self):
        """Default initial condition used in the original script."""
        return torch.tensor([1.0, 0.5], dtype=self.dtype, device=self.device)

    def default_parameters(self):
        """Default parameter vector used in the original script."""
        return torch.tensor([10.0, 5.0, 3.0, 1.0, 3.0], dtype=self.dtype, device=self.device)


def plot_trajectory(solution, output_path=OUTPUT_DIR / "population_system.svg"):
    """Plot the phase-plane trajectory of the two population states."""
    solution_plot = solution.detach().cpu().numpy()

    fig, ax = plt.subplots(figsize=(10, 6), constrained_layout=True)
    ax.plot(solution_plot[:, 0], solution_plot[:, 1], linewidth=5)
    ax.set_xlabel("Prey Population")
    ax.set_ylabel("Predator Population")
    ax.set_title("Population System Trajectory")
    fig.savefig(output_path)
    plt.close(fig)


def run_demo():
    """Run the default population-system example and save a trajectory plot."""
    solver = PopulationSystem()
    solution = solver.solve(
        solver.default_initial_condition(),
        solver.default_parameters(),
        show_progress=True,
    )
    plot_trajectory(solution)
    return solver, solution


if __name__ == "__main__":
    run_demo()
